apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maskani-api
  namespace: sandbox
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - api.sandbox.maskani.co.ke
    secretName: maskani-api-tls
  rules:
    - host: api.sandbox.maskani.co.ke
      http:
        paths:
        - path: /
          backend:
            serviceName: maskani-api
            servicePort: 3030