apiVersion: v1
kind: Service
metadata:
  name: maskani-api
  labels:
    app:  core
    tier: backend
    type: app
    name: maskani-api
spec:
  ports:
  - port: 3030
    targetPort: 3000
  selector:
    app: core
    tier: backend
    type: app
    name: maskani-api